In [ ]:
import numpy as np
import pandas as pd
import json, sys, regex, os
import random
import requests

In [ ]:
url = 'https://recruitment.aimtechnologies.co/ai-tasks'

In [ ]:
original_data = pd.read_csv('/content/dialect_dataset.csv')
original_data.head()

                    id dialect
0  1175358310087892992      IQ
1  1175416117793349632      IQ
2  1175450108898565888      IQ
3  1175471073770573824      IQ
4  1175496913145217024      IQ

In [ ]:
original_data.shape

(458197, 2)

**Requesting data as batches, each batch is 1000 tweet.**

In [ ]:
%%time

size = len(original_data)
tweets = []
start = 0
# Iterate over all data with batches, each one = 1000 row data.
for b, end in enumerate(range(1000,size, 1000)):
    batch = original_data['id'][start:end].tolist()
    batch = [str(num) for num in batch]
    response_API = requests.post(url, json= batch)
    print("Batch # {:<8}   start {:<8} end  {:<8} is :{:<8}".format(b+1, start, end, response_API.status_code))
    data = response_API.content
    parse_json = json.loads(data)
    tmp = [parse_json[id] for id in batch if id in parse_json]

    tweets.extend(tmp)
    start = end

# we stopped at the end variable which is indicate the last request number dat.So we will take the rest data starting form end.
batch = original_data['id'][end:].tolist()
batch = [str(num) for num in batch]
response_API = requests.post(url, json= batch)
data = response_API.content
parse_json = json.loads(data)
tmp = [parse_json[id] for id in batch if id in parse_json]
tweets.extend(tmp)
print("Batch # {:<8}   start {:<8} end  {:<8} is :{:<8}".format(b+2, start, size, response_API.status_code))

Batch # 1          start 0        end  1000     is :200
Batch # 2          start 1000     end  2000     is :200
Batch # 3          start 2000     end  3000     is :200
Batch # 4          start 3000     end  4000     is :200
Batch # 5          start 4000     end  5000     is :200
Batch # 6          start 5000     end  6000     is :200
Batch # 7          start 6000     end  7000     is :200
Batch # 8          start 7000     end  8000     is :200
Batch # 9          start 8000     end  9000     is :200
Batch # 10         start 9000     end  10000    is :200
Batch # 11         start 10000    end  11000    is :200
Batch # 12         start 11000    end  12000    is :200
Batch # 13         start 12000    end  13000    is :200
Batch # 14         start 13000    end  14000    is :200
Batch # 15         start 14000    end  15000    is :200
Batch # 16         start 15000    end  16000    is :200
Batch # 17         start 16000    end  17000    is :200
Batch # 18         start 17000    end  18000    is :200
Batch # 19         start 18000    end  19000    is :200
Batch # 20         start 19000    end  20000    is :200
Batch # 21         start 20000    end  21000    is :200
Batch # 22         start 21000    end  22000    is :200
Batch # 23         start 22000    end  23000    is :200
Batch # 24         start 23000    end  24000    is :200
Batch # 25         start 24000    end  25000    is :200
Batch # 26         start 25000    end  26000    is :200
Batch # 27         start 26000    end  27000    is :200
Batch # 28         start 27000    end  28000    is :200
Batch # 29         start 28000    end  29000    is :200
Batch # 30         start 29000    end  30000    is :200
Batch # 31         start 30000    end  31000    is :200
Batch # 32         start 31000    end  32000    is :200
Batch # 33         start 32000    end  33000    is :200
Batch # 34         start 33000    end  34000    is :200
Batch # 35         start 34000    end  35000    is :200
Batch # 36         start 35000    end  36000    is :200
Batch # 37         start 36000    end  37000    is :200
Batch # 38         start 37000    end  38000    is :200
Batch # 39         start 38000    end  39000    is :200
Batch # 40         start 39000    end  40000    is :200
Batch # 41         start 40000    end  41000    is :200
Batch # 42         start 41000    end  42000    is :200
Batch # 43         start 42000    end  43000    is :200
Batch # 44         start 43000    end  44000    is :200
Batch # 45         start 44000    end  45000    is :200
Batch # 46         start 45000    end  46000    is :200
Batch # 47         start 46000    end  47000    is :200
Batch # 48         start 47000    end  48000    is :200
Batch # 49         start 48000    end  49000    is :200
Batch # 50         start 49000    end  50000    is :200
Batch # 51         start 50000    end  51000    is :200
Batch # 52         start 51000    end  52000    is :200
Batch # 53         start 52000    end  53000    is :200
Batch # 54         start 53000    end  54000    is :200
Batch # 55         start 54000    end  55000    is :200
Batch # 56         start 55000    end  56000    is :200
Batch # 57         start 56000    end  57000    is :200
Batch # 58         start 57000    end  58000    is :200
Batch # 59         start 58000    end  59000    is :200
Batch # 60         start 59000    end  60000    is :200
Batch # 61         start 60000    end  61000    is :200
Batch # 62         start 61000    end  62000    is :200
Batch # 63         start 62000    end  63000    is :200
Batch # 64         start 63000    end  64000    is :200
Batch # 65         start 64000    end  65000    is :200
Batch # 66         start 65000    end  66000    is :200
Batch # 67         start 66000    end  67000    is :200
Batch # 68         start 67000    end  68000    is :200
Batch # 69         start 68000    end  69000    is :200
Batch # 70         start 69000    end  70000    is :200
Batch # 71         start 70000    end  71000    is :200
Batch # 72         start 71000    end  72000    is :200
Batch # 73         start 72000    end  73000    is :200
Batch # 74         start 73000    end  74000    is :200
Batch # 75         start 74000    end  75000    is :200
Batch # 76         start 75000    end  76000    is :200
Batch # 77         start 76000    end  77000    is :200
Batch # 78         start 77000    end  78000    is :200
Batch # 79         start 78000    end  79000    is :200
Batch # 80         start 79000    end  80000    is :200
Batch # 81         start 80000    end  81000    is :200
Batch # 82         start 81000    end  82000    is :200
Batch # 83         start 82000    end  83000    is :200
Batch # 84         start 83000    end  84000    is :200
Batch # 85         start 84000    end  85000    is :200
Batch # 86         start 85000    end  86000    is :200
Batch # 87         start 86000    end  87000    is :200
Batch # 88         start 87000    end  88000    is :200
Batch # 89         start 88000    end  89000    is :200
Batch # 90         start 89000    end  90000    is :200
Batch # 91         start 90000    end  91000    is :200
Batch # 92         start 91000    end  92000    is :200
Batch # 93         start 92000    end  93000    is :200
Batch # 94         start 93000    end  94000    is :200
Batch # 95         start 94000    end  95000    is :200
Batch # 96         start 95000    end  96000    is :200
Batch # 97         start 96000    end  97000    is :200
Batch # 98         start 97000    end  98000    is :200
Batch # 99         start 98000    end  99000    is :200
Batch # 100        start 99000    end  100000   is :200
Batch # 101        start 100000   end  101000   is :200
Batch # 102        start 101000   end  102000   is :200
Batch # 103        start 102000   end  103000   is :200
Batch # 104        start 103000   end  104000   is :200
Batch # 105        start 104000   end  105000   is :200
Batch # 106        start 105000   end  106000   is :200
Batch # 107        start 106000   end  107000   is :200
Batch # 108        start 107000   end  108000   is :200
Batch # 109        start 108000   end  109000   is :200
Batch # 110        start 109000   end  110000   is :200
Batch # 111        start 110000   end  111000   is :200
Batch # 112        start 111000   end  112000   is :200
Batch # 113        start 112000   end  113000   is :200
Batch # 114        start 113000   end  114000   is :200
Batch # 115        start 114000   end  115000   is :200
Batch # 116        start 115000   end  116000   is :200
Batch # 117        start 116000   end  117000   is :200
Batch # 118        start 117000   end  118000   is :200
Batch # 119        start 118000   end  119000   is :200
Batch # 120        start 119000   end  120000   is :200
Batch # 121        start 120000   end  121000   is :200
Batch # 122        start 121000   end  122000   is :200
Batch # 123        start 122000   end  123000   is :200
Batch # 124        start 123000   end  124000   is :200
Batch # 125        start 124000   end  125000   is :200
Batch # 126        start 125000   end  126000   is :200
Batch # 127        start 126000   end  127000   is :200
Batch # 128        start 127000   end  128000   is :200
Batch # 129        start 128000   end  129000   is :200
Batch # 130        start 129000   end  130000   is :200
Batch # 131        start 130000   end  131000   is :200
Batch # 132        start 131000   end  132000   is :200
Batch # 133        start 132000   end  133000   is :200
Batch # 134        start 133000   end  134000   is :200
Batch # 135        start 134000   end  135000   is :200
Batch # 136        start 135000   end  136000   is :200
Batch # 137        start 136000   end  137000   is :200
Batch # 138        start 137000   end  138000   is :200
Batch # 139        start 138000   end  139000   is :200
Batch # 140        start 139000   end  140000   is :200
Batch # 141        start 140000   end  141000   is :200
Batch # 142        start 141000   end  142000   is :200
Batch # 143        start 142000   end  143000   is :200
Batch # 144        start 143000   end  144000   is :200
Batch # 145        start 144000   end  145000   is :200
Batch # 146        start 145000   end  146000   is :200
Batch # 147        start 146000   end  147000   is :200
Batch # 148        start 147000   end  148000   is :200
Batch # 149        start 148000   end  149000   is :200
Batch # 150        start 149000   end  150000   is :200
Batch # 151        start 150000   end  151000   is :200
Batch # 152        start 151000   end  152000   is :200
Batch # 153        start 152000   end  153000   is :200
Batch # 154        start 153000   end  154000   is :200
Batch # 155        start 154000   end  155000   is :200
Batch # 156        start 155000   end  156000   is :200
Batch # 157        start 156000   end  157000   is :200
Batch # 158        start 157000   end  158000   is :200
Batch # 159        start 158000   end  159000   is :200
Batch # 160        start 159000   end  160000   is :200
Batch # 161        start 160000   end  161000   is :200
Batch # 162        start 161000   end  162000   is :200
Batch # 163        start 162000   end  163000   is :200
Batch # 164        start 163000   end  164000   is :200
Batch # 165        start 164000   end  165000   is :200
Batch # 166        start 165000   end  166000   is :200
Batch # 167        start 166000   end  167000   is :200
Batch # 168        start 167000   end  168000   is :200
Batch # 169        start 168000   end  169000   is :200
Batch # 170        start 169000   end  170000   is :200
Batch # 171        start 170000   end  171000   is :200
Batch # 172        start 171000   end  172000   is :200
Batch # 173        start 172000   end  173000   is :200
Batch # 174        start 173000   end  174000   is :200
Batch # 175        start 174000   end  175000   is :200
Batch # 176        start 175000   end  176000   is :200
Batch # 177        start 176000   end  177000   is :200
Batch # 178        start 177000   end  178000   is :200
Batch # 179        start 178000   end  179000   is :200
Batch # 180        start 179000   end  180000   is :200
Batch # 181        start 180000   end  181000   is :200
Batch # 182        start 181000   end  182000   is :200
Batch # 183        start 182000   end  183000   is :200
Batch # 184        start 183000   end  184000   is :200
Batch # 185        start 184000   end  185000   is :200
Batch # 186        start 185000   end  186000   is :200
Batch # 187        start 186000   end  187000   is :200
Batch # 188        start 187000   end  188000   is :200
Batch # 189        start 188000   end  189000   is :200
Batch # 190        start 189000   end  190000   is :200
Batch # 191        start 190000   end  191000   is :200
Batch # 192        start 191000   end  192000   is :200
Batch # 193        start 192000   end  193000   is :200
Batch # 194        start 193000   end  194000   is :200
Batch # 195        start 194000   end  195000   is :200
Batch # 196        start 195000   end  196000   is :200
Batch # 197        start 196000   end  197000   is :200
Batch # 198        start 197000   end  198000   is :200
Batch # 199        start 198000   end  199000   is :200
Batch # 200        start 199000   end  200000   is :200
Batch # 201        start 200000   end  201000   is :200
Batch # 202        start 201000   end  202000   is :200
Batch # 203        start 202000   end  203000   is :200
Batch # 204        start 203000   end  204000   is :200
Batch # 205        start 204000   end  205000   is :200
Batch # 206        start 205000   end  206000   is :200
Batch # 207        start 206000   end  207000   is :200
Batch # 208        start 207000   end  208000   is :200
Batch # 209        start 208000   end  209000   is :200
Batch # 210        start 209000   end  210000   is :200
Batch # 211        start 210000   end  211000   is :200
Batch # 212        start 211000   end  212000   is :200
Batch # 213        start 212000   end  213000   is :200
Batch # 214        start 213000   end  214000   is :200
Batch # 215        start 214000   end  215000   is :200
Batch # 216        start 215000   end  216000   is :200
Batch # 217        start 216000   end  217000   is :200
Batch # 218        start 217000   end  218000   is :200
Batch # 219        start 218000   end  219000   is :200
Batch # 220        start 219000   end  220000   is :200
Batch # 221        start 220000   end  221000   is :200
Batch # 222        start 221000   end  222000   is :200
Batch # 223        start 222000   end  223000   is :200
Batch # 224        start 223000   end  224000   is :200
Batch # 225        start 224000   end  225000   is :200
Batch # 226        start 225000   end  226000   is :200
Batch # 227        start 226000   end  227000   is :200
Batch # 228        start 227000   end  228000   is :200
Batch # 229        start 228000   end  229000   is :200
Batch # 230        start 229000   end  230000   is :200
Batch # 231        start 230000   end  231000   is :200
Batch # 232        start 231000   end  232000   is :200
Batch # 233        start 232000   end  233000   is :200
Batch # 234        start 233000   end  234000   is :200
Batch # 235        start 234000   end  235000   is :200
Batch # 236        start 235000   end  236000   is :200
Batch # 237        start 236000   end  237000   is :200
Batch # 238        start 237000   end  238000   is :200
Batch # 239        start 238000   end  239000   is :200
Batch # 240        start 239000   end  240000   is :200
Batch # 241        start 240000   end  241000   is :200
Batch # 242        start 241000   end  242000   is :200
Batch # 243        start 242000   end  243000   is :200
Batch # 244        start 243000   end  244000   is :200
Batch # 245        start 244000   end  245000   is :200
Batch # 246        start 245000   end  246000   is :200
Batch # 247        start 246000   end  247000   is :200
Batch # 248        start 247000   end  248000   is :200
Batch # 249        start 248000   end  249000   is :200
Batch # 250        start 249000   end  250000   is :200
Batch # 251        start 250000   end  251000   is :200
Batch # 252        start 251000   end  252000   is :200
Batch # 253        start 252000   end  253000   is :200
Batch # 254        start 253000   end  254000   is :200
Batch # 255        start 254000   end  255000   is :200
Batch # 256        start 255000   end  256000   is :200
Batch # 257        start 256000   end  257000   is :200
Batch # 258        start 257000   end  258000   is :200
Batch # 259        start 258000   end  259000   is :200
Batch # 260        start 259000   end  260000   is :200
Batch # 261        start 260000   end  261000   is :200
Batch # 262        start 261000   end  262000   is :200
Batch # 263        start 262000   end  263000   is :200
Batch # 264        start 263000   end  264000   is :200
Batch # 265        start 264000   end  265000   is :200
Batch # 266        start 265000   end  266000   is :200
Batch # 267        start 266000   end  267000   is :200
Batch # 268        start 267000   end  268000   is :200
Batch # 269        start 268000   end  269000   is :200
Batch # 270        start 269000   end  270000   is :200
Batch # 271        start 270000   end  271000   is :200
Batch # 272        start 271000   end  272000   is :200
Batch # 273        start 272000   end  273000   is :200
Batch # 274        start 273000   end  274000   is :200
Batch # 275        start 274000   end  275000   is :200
Batch # 276        start 275000   end  276000   is :200
Batch # 277        start 276000   end  277000   is :200
Batch # 278        start 277000   end  278000   is :200
Batch # 279        start 278000   end  279000   is :200
Batch # 280        start 279000   end  280000   is :200
Batch # 281        start 280000   end  281000   is :200
Batch # 282        start 281000   end  282000   is :200
Batch # 283        start 282000   end  283000   is :200
Batch # 284        start 283000   end  284000   is :200
Batch # 285        start 284000   end  285000   is :200
Batch # 286        start 285000   end  286000   is :200
Batch # 287        start 286000   end  287000   is :200
Batch # 288        start 287000   end  288000   is :200
Batch # 289        start 288000   end  289000   is :200
Batch # 290        start 289000   end  290000   is :200
Batch # 291        start 290000   end  291000   is :200
Batch # 292        start 291000   end  292000   is :200
Batch # 293        start 292000   end  293000   is :200
Batch # 294        start 293000   end  294000   is :200
Batch # 295        start 294000   end  295000   is :200
Batch # 296        start 295000   end  296000   is :200
Batch # 297        start 296000   end  297000   is :200
Batch # 298        start 297000   end  298000   is :200
Batch # 299        start 298000   end  299000   is :200
Batch # 300        start 299000   end  300000   is :200
Batch # 301        start 300000   end  301000   is :200
Batch # 302        start 301000   end  302000   is :200
Batch # 303        start 302000   end  303000   is :200
Batch # 304        start 303000   end  304000   is :200
Batch # 305        start 304000   end  305000   is :200
Batch # 306        start 305000   end  306000   is :200
Batch # 307        start 306000   end  307000   is :200
Batch # 308        start 307000   end  308000   is :200
Batch # 309        start 308000   end  309000   is :200
Batch # 310        start 309000   end  310000   is :200
Batch # 311        start 310000   end  311000   is :200
Batch # 312        start 311000   end  312000   is :200
Batch # 313        start 312000   end  313000   is :200
Batch # 314        start 313000   end  314000   is :200
Batch # 315        start 314000   end  315000   is :200
Batch # 316        start 315000   end  316000   is :200
Batch # 317        start 316000   end  317000   is :200
Batch # 318        start 317000   end  318000   is :200
Batch # 319        start 318000   end  319000   is :200
Batch # 320        start 319000   end  320000   is :200
Batch # 321        start 320000   end  321000   is :200
Batch # 322        start 321000   end  322000   is :200
Batch # 323        start 322000   end  323000   is :200
Batch # 324        start 323000   end  324000   is :200
Batch # 325        start 324000   end  325000   is :200
Batch # 326        start 325000   end  326000   is :200
Batch # 327        start 326000   end  327000   is :200
Batch # 328        start 327000   end  328000   is :200
Batch # 329        start 328000   end  329000   is :200
Batch # 330        start 329000   end  330000   is :200
Batch # 331        start 330000   end  331000   is :200
Batch # 332        start 331000   end  332000   is :200
Batch # 333        start 332000   end  333000   is :200
Batch # 334        start 333000   end  334000   is :200
Batch # 335        start 334000   end  335000   is :200
Batch # 336        start 335000   end  336000   is :200
Batch # 337        start 336000   end  337000   is :200
Batch # 338        start 337000   end  338000   is :200
Batch # 339        start 338000   end  339000   is :200
Batch # 340        start 339000   end  340000   is :200
Batch # 341        start 340000   end  341000   is :200
Batch # 342        start 341000   end  342000   is :200
Batch # 343        start 342000   end  343000   is :200
Batch # 344        start 343000   end  344000   is :200
Batch # 345        start 344000   end  345000   is :200
Batch # 346        start 345000   end  346000   is :200
Batch # 347        start 346000   end  347000   is :200
Batch # 348        start 347000   end  348000   is :200
Batch # 349        start 348000   end  349000   is :200
Batch # 350        start 349000   end  350000   is :200
Batch # 351        start 350000   end  351000   is :200
Batch # 352        start 351000   end  352000   is :200
Batch # 353        start 352000   end  353000   is :200
Batch # 354        start 353000   end  354000   is :200
Batch # 355        start 354000   end  355000   is :200
Batch # 356        start 355000   end  356000   is :200
Batch # 357        start 356000   end  357000   is :200

In [ ]:
# save data and upload on my drive
data = pd.DataFrame({'id': original_data['id'].tolist(), 
                     'tweets': tweets,
                     'dialect': original_data['dialect'].tolist()})

data.to_csv('Ara_dialect.csv', index=False)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458197 entries, 0 to 458196
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   id       458197 non-null  int64
 1   tweets   458197 non-null  object
 2   dialect  458197 non-null  object
dtypes: int64(1), object(2)
memory usage: 10.5+ MB

In [ ]:
data.dialect.value_counts()

EG    57636
PL    43742
KW    42109
LY    36499
QA    31069
JO    27921
LB    27617
SA    26832
AE    26296
BH    26292
OM    19116
SY    16242
DZ    16183
IQ    15497
SD    14434
MA    11539
YE     9927
TN     9246
Name: dialect, dtype: int64

In [ ]:
data.head()

,id,tweets,dialect
0,1175358310087892992,@Nw8ieJUwaCAAreT لكن بالنهاية .. ينتفض .. يغير .,IQ
1,1175416117793349632,@7zNqXP0yrODdRjK يعني هذا محسوب على البشر .. ح...,IQ
2,1175450108898565888,@KanaanRema مبين من كلامه خليجي,IQ
3,1175471073770573824,@HAIDER76128900 يسلملي مرورك وروحك الحلوه💐,IQ
4,1175496913145217024,@hmo2406 وين هل الغيبه اخ محمد 🌸🌺,IQ